- name: Download the MySQL 5.7 Community Release RPM Linux
  get_url:
    url: https://repo.mysql.com//mysql57-community-release-el7-11.noarch.rpm
    dest: /tmp/mysql57-community-release-el7-11.noarch.rpm

- name: Import MySQL GPG Key Linux #import GPG key before installing package
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: Install the MySQL 5.7 Community Release RPM Linux
  yum:
    name: /tmp/mysql57-community-release-el7-11.noarch.rpm
    state: present

- name: Install MySQL Linux
  package:
    name: mysql-community-server
    state: present
  notify:
  - Enable MySQL
  - Restart MySQL

# - name: Download the MySQL 5.7 Community Release RPM Linux
#   get_url:
#     url: https://repo.mysql.com/mysql57-community-release-el7-11.noarch.rpm
#     dest: /tmp/mysql57-community-release-el7-11.noarch.rpm

# - name: Import MySQL GPG Key
#   rpm_key:
#     state: absent
#     key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

# - name: Install the MySQL 5.7 Community Release RPM Linux
#   yum:
#     name: /tmp/mysql57-community-release-el7-11.noarch.rpm
#     state: absent

# - name: Install MySQL Server
#   package:
#     name: mysql-community-server
#     state: absent